http://localhost:3000

###
PUT  http://localhost:3000/user/add
Content-Type: application/json

{
    "name" : "anjasmarancxzxca",          
    "password" : "abc",      
    "email" :"78",        
    "avatar" :"78",
    "nim": 530,        
    "personalNumber": 78, 
    "telegramId": 78     
}

###
POST http://localhost:3000/user/a6d9c8aa-0031-4965-8c0b-43f5b06480bf
Content-Type: application/json

{
    "name": "anjaayyy",          
    "password": "abc",      
    "email": "78",        
    "avatar": "78",
    "nim": 530,        
    "personalNumber": 78, 
    "telegramId": 78      
}

###
DELETE  http://localhost:3000/user/e8c71aff-d44c-4b6c-a5b0-972e2f91c667


###
GET  http://localhost:3000/user/